NAME_IMAGE_ORIGIN   = 'petra'
FORMAT_IMAGE_ORIGIN = '.png'
PATH_IMAGE_ORIGIN   = 'image/'+NAME_IMAGE_ORIGIN+FORMAT_IMAGE_ORIGIN

PATH_IMAGE_RESULT = 'image-result'
NAME_IMAGE_RESULT = NAME_IMAGE_ORIGIN+'_result_'